version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
      - JENKINS_URL=http://jenkins-test:8080
      - JENKINS_USER=admin
      - JENKINS_API_TOKEN=test-token
      - OPENAI_API_KEY=test-key
      - REDIS_URL=redis://redis-test:6379
      - MONGODB_URL=mongodb://mongodb-test:27017
      - TESTING=true
    depends_on:
      jenkins-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
      mongodb-test:
        condition: service_healthy
    networks:
      - test_net
    command: ["pytest", "-v", "--cov=langchain_jenkins"]

  jenkins-test:
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
    environment:
      - JENKINS_ADMIN_PASSWORD=admin
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - test_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  redis-test:
    image: redis:7-alpine
    networks:
      - test_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  mongodb-test:
    image: mongo:6
    networks:
      - test_net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  test_net:
    driver: bridge