apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jenkins.yaml
  - web.yaml
  - github-sync.yaml
  - monitoring.yaml
  - redis.yaml
  - mongodb.yaml

commonLabels:
  app.kubernetes.io/name: jenkins-agent
  app.kubernetes.io/managed-by: kustomize

namespace: jenkins-agent
