apiVersion: v1
kind: Service
metadata:
  name: monitoring
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: grafana
    - port: 9090
      targetPort: 9090
      name: prometheus
    - port: 9100
      targetPort: 9100
      name: node-exporter
  selector:
    app: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: monitoring
          image: jenkins-agent-monitoring:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: grafana
            - containerPort: 9090
              name: prometheus
            - containerPort: 9100
              name: node-exporter
          env:
            - name: JENKINS_URL
              value: http://jenkins:8080
            - name: JENKINS_USER
              value: admin
            - name: JENKINS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jenkins-secrets
                  key: api-token
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus
            - name: grafana-data
              mountPath: /var/lib/grafana
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi